# Generated by Django 2.1.4 on 2019-01-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_and_dance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
