# Generated by Django 2.1.4 on 2019-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_and_dance', '0004_auto_20190102_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='style',
            field=models.CharField(choices=[('foxtrot', 'Foxtrot'), ('quickstep', 'Quickstep'), ('tango', 'Tango'), ('vwaltz', 'Viennese Waltz'), ('waltz', 'Waltz'), ('chacha', 'Cha Cha'), ('east-coast', 'East Coast Swing'), ('jive', 'Jive'), ('paso-doble', 'Paso Doble'), ('rumba', 'Rumba'), ('bachata', 'Bachata'), ('bolero', 'Bolero'), ('mambo', 'Mambo'), ('salsa', 'Salsa'), ('west-coast', 'West Coast Swing'), ('czech-polka', 'Czech Polka'), ('default', 'Unknown')], default='default', max_length=30),
        ),
    ]
