# Generated by Django 2.1.4 on 2019-01-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_and_dance', '0005_auto_20190102_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
